### ISSUE TITLE
[AIFlow] Supports the `pause_job_scheduling` to pause the specified job scheduling

### ISSUE THREAD

**Issue by syntomic** [flink-extended/ai-flow#146]
### Describe the feature

Hope support pause_job_scheduling for sometimes a job is periodic, now only support pause_workflow_scheduling

**Comment by SteNicholas** [comment]
@syntomic, IMO the `pause_job_scheduling` which pause the periodic job scheduling makes sense to me. Do you have interest to introduce this interface?
