### ISSUE TITLE
[Airflow] The remote logging supports the current log mechanism

### ISSUE THREAD

**Issue by SteNicholas** [flink-extended/ai-flow#172]
`FileTaskHandler`, a python log handler that handles and reads task instance logs, supports the current log mechanism which uses `seq_num` and `try_number` to name the log file. The remote log handler like `S3TaskHandler` should support the log mechanism.

**Comment by aqua7regia** [comment]
I saw the log file path has been renamed like "{seq_num}_{try_number}.log" if seq_num in task_instance when the FileTaskHandler initial the log file relative path, and the remote log handler still use the name like "{try_number}.log" to upload or download, that may cause the bug.


file_task_handler.py line 247:
```
if hasattr(ti, 'seq_num') and ti.seq_num > 0:
    number = '{}_{}'.format(ti.seq_num, ti.try_number)
else:
    number = ti.try_number
relative_path = self._render_filename(ti, number)
```

s3_task_handler.py line 62:
```
self.log_relative_path = self._render_filename(ti, ti.try_number)
```

And GCS and Azure log handlers have the same problem.

**Comment by SteNicholas** [comment]
@aqua7regia , thanks for your reporter for the remote logging handler. I have assigned to you and thanks for your contribution.
