### ISSUE TITLE
[Flink AI Flow] Is 'Artifact' concept in ai flow is per-project or globally?

### ISSUE THREAD

**Issue by bgeng777** [flink-extended/ai-flow#19]
### Describe the feature
Currently, Artifact is identified by its name. As a result, different projects can not register artifacts with same name. 
It is worthwhile to discuss if this behavior is by design(i.e. artifacts are globally unique) or the artifact can be per-project.

![image](https://user-images.githubusercontent.com/80749729/138405134-b59e0800-48af-42c6-996e-d6c291b87214.png)

**Comment by jiangxin369** [comment]
We remove artifact model in v0.4
