### ISSUE TITLE
How to use with Alink? What's the difference between ai-flow and Alink Pipeline?

### ISSUE THREAD

**Issue by percylleo** [flink-extended/ai-flow#256]

**Comment by SteNicholas** [comment]
@percylleo, Alink is the Machine Learning algorithm platform based on Flink, but the AIFlow is a framework that bridges big data and artificial intelligence and manages the entire machine learning lifecycle as a unified workflow. You could use Alink to write the model training job in the workflow which is defined using AIFlow SDK.
