### ISSUE TITLE
[AI Flow] update_dataset should send an event to trigger the job defined by action_on_dataset_event

### ISSUE THREAD

**Issue by syntomic** [flink-extended/ai-flow#95]
### Describe the feature

update_dataset should send an event to tigger the job defined by action_on_dataset_event

**Comment by SteNicholas** [comment]
@syntomic , thanks for the bug reportor of the `action_on_dataset_event`. This interace has temporarily removed in 0.2.2 version. In future, this interface could provide the users when `register_dataset` and `update_dataset` supports to send the event about the dataset.
